### ISSUE TITLE
[Setting] 프로젝트 세팅 

### ISSUE THREAD

**Issue by HELLOHIDI** [SOPT-Joint-Seminar-Toss/Toss_iOS#1]
## 🛠 Issue
- 프로젝트 세팅 

## 📋 To-do
- [x] 폰트 정리
- [x] Extension 코드 추가
- [x] Constant 파일에 Image 추가
- [x] Constant 파일에 color 추가
