### ISSUE TITLE
[Network] 공동 구매 API 서버 통신 구현 

### ISSUE THREAD

**Issue by HELLOHIDI** [SOPT-Joint-Seminar-Toss/Toss_iOS#35]
## 🛠 Issue
- 공동 구매 API 서버 통신 구현 

## 📋 To-do
- [ ] 공동 구매 API 서버 데이터 벋아오기
- [ ] 각 셀 별로 해당 종료 시간 띄우기
- [ ] 시간이 지날때마다 1초씩 감소되도록 하기
