### ISSUE TITLE
[Style] 토스 페이구매하기&선물하기 UI 구현

### ISSUE THREAD

**Issue by shinzz410** [SOPT-Joint-Seminar-Toss/Toss_iOS#7]
## 🛠 Issue
- 토스 페이 구매하기 페이지 UI 구현 (1)
- 토스 선물하기 페이지 UI 구현 (2)

## 📋 To-do
- [ ] (1) 네비게이션 바 구현
- [x] (1) Table View 구현
- [x] (1) 상품정보와 후기 swipe 구현
- [ ] (1) Back Button 구현
💫
- [ ] (2) TextView + 카드 골라주기 구현
- [ ] (2) 네비게이션 바 구현
- [ ] (2) 수정 완료 버튼 구현 ( 누르면 네비게이션 바 없어지고, 수정 완료 버튼 등장)
- [ ] (2) textview 글자수
